
trigger: 
- master

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  artifactName: 'fordevsprod-Deploy'

stages:
- stage: BuildAndValidations
  displayName: Build do App em React
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'npm install'

    - script: npm run build
      displayName: 'npm run build'

    # - script: npm run test
    #   displayName: 'npm run test'

    - task: PublishBuildArtifacts@1
      displayName: 'Publishing artifact'
      inputs:
        PathtoPublish: '$(Pipeline.Workspace)/artifacts'
        ArtifactName: 'MyArtifact'



- stage: DeployInAzureStorage
  displayName: Deploy in Azure Storage
  jobs:
  - deployment: Upload
    displayName: Upload files
    environment: PRD
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          
          - task: DownloadPipelineArtifact@2
            displayName: Download do Artifact gerado no stage de Build
            inputs:
              buildType: 'current'
              artifactName: $(artifactWebApp)
              targetPath: '$(System.DefaultWorkingDirectory)/publish'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'fordevs-connections-services'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage blob upload-batch --account-name fordevsprod --account-key ''I8psYVfH4alrRJZX1Dg00dy6OhyTrPZmzxq/N6NlGtak9Q9nmfsEqEfKZCySmX5KB2UUha0C2+PZ+AStC11Uxg=='' --destination ''$web'' --source $(System.DefaultWorkingDirectory)/publish/'
